import { supportedLocales } from "@/middleware";
import "./globals.css";
import type { Metadata, NextPageContext } from "next";
import { Inter } from "next/font/google";
import { NextRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return supportedLocales.map((l) => ({
    locale: l,
  }));
}

export default function RootLayout({
  params,
  children,
}: {
  params: { locale: string };
  children: React.ReactNode;
}) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
