import { getGraphqlClient } from "@/lib/graphql-client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SiteLayout from "./_SiteLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (!process.env.SITE_ID || !process.env.CMS_TOKEN) {
  throw new Error("No SITE_ID or CMS_TOKEN variable");
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const client = getGraphqlClient(process.env.CMS_TOKEN!);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SiteLayout client={client} siteId={process.env.SITE_ID!}>
          {children}
        </SiteLayout>
      </body>
    </html>
  );
}
